11-ActorManagementApp/Controllers/BiographyController.cs
using _11_ActorManagementApp.ProjectModels;
using _11_ActorManagementApp.ViewModels.BiographyVM;
using ActorManagement.Models.EntityModels;
using ActorManagement.Services.Contracts.AllContracts;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace _11_ActorManagementApp.Controllers
{
    public class BiographyController : Controller
    {
        private readonly IUnitService _unitService;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly FileUpload _fileUpload;
        public BiographyController(IUnitService unitService, IMapper mapper, IWebHostEnvironment webHostEnvironment)
        {
            this._unitService = unitService;
            this._mapper = mapper;
            this._webHostEnvironment = webHostEnvironment;
            this._fileUpload = new FileUpload(_webHostEnvironment.WebRootPath);
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        private async Task PopulateActors()
        {
            IEnumerable<Actor> actors = (await _unitService.ActorService.GetAllActorsAsync()).ToList();
            ViewBag.ActorIdType = new SelectList(actors, "ActorId", "FirstName");
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            //List<Actor> actors = (await _unitService.ActorService.GetAllActorsAsync()).ToList();
            //ViewBag.ActorIdType = new SelectList(actors, "ActorId", "FirstName");
            await PopulateActors();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(BiographyAddVM biographyAddVM)
        {
            if (!ModelState.IsValid)
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                ViewBag.Errors = errors; // Pass errors to the view
                ViewBag.Message = "Sorry! Invalid information, please enter valid information.";
                await PopulateActors();
                return View(biographyAddVM);
            }
            //Check if the actor already has a biography
            Biography? existBiography = await _unitService.BiographyService.GetBiographyByActorIdAsync(biographyAddVM.ActorId);
            if (existBiography != null)
            {
                ViewBag.Message = "This actor already has a biography, please update the existing biography.";
                await PopulateActors();
                return View(biographyAddVM);
            }
            //Ensure biography description file is provided
            if (biographyAddVM.DescriptionFile == null)
            {
                ViewBag.Message = "Please upload actor description.";
                await PopulateActors();
                return View(biographyAddVM);
            }
            //Ensure at least one image file is provided
            if (biographyAddVM.BioImages == null)
            {
                ViewBag.Message = "Please upload at least one actor image.";
                await PopulateActors();
                return View(biographyAddVM);
            }
            else
            {
                try
                {
                    //Upload description file(image or PDF)
                    string descriptionFolder = "description-bio";
                    //Call ImageOrPdfUploadAsync method to upload actor description
                    string descriptionName = await _fileUpload.ImageOrPdfUploadAsync(biographyAddVM.DescriptionFile, descriptionFolder);
                    if (!string.IsNullOrEmpty(descriptionName))
                    {
                        biographyAddVM.DescriptionFileName = descriptionName;
                    }

                    //Upload actor images(multiple)
                    string imageFolder = "images-bio";
                    //Call MultipleActorImagesAsync method to upload actor images
                    List<string> imageNames = await _fileUpload.MultipleImageUploadAsync(biographyAddVM.BioImages, imageFolder);
                    if (imageNames != null && imageNames.Any())
                    {
                        biographyAddVM.BiographyImages = imageNames
                            .Select(img => new BiographyImage()
                            {
                                ImageName = img
                            }).ToList();
                    }

                    //Save biography to the database
                    //Map viewmodel to domain model
                    Biography biography = _mapper.Map<Biography>(biographyAddVM);
                    await _unitService.BiographyService.AddBiographyAsync(biography);
                    bool isSaved = await _unitService.SaveChangesAsync();

                    //Provide feedback
                    TempData["Message"] = isSaved
                        ? "Biography information has been saved successfully, thanks"
                        : "Sorry! Information hasn't been saved";

                    return RedirectToAction("Index", "Actor");
                }
                catch (InvalidOperationException ex) //Catch only expected errors
                {
                    ViewBag.Message = $"Error: {ex.Message}";
                    await PopulateActors();
                    return View(biographyAddVM);
                }
                catch //Catch unexpected errors
                {
                    ViewBag.Message = "An unexpected error occured. Please try again.";
                    await PopulateActors();
                    return View(biographyAddVM);
                }
            }
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid? biographyId)
        {

            if (biographyId == null)
            {
                ViewBag.Message = "Sorry! there is no biography found.";
                await PopulateActors();
                return View(new BiographyEditVM());
            }
            //Reterieve biography by id
            Biography? existBiography = await _unitService.BiographyService.GetBiographyByIdAsync(biographyId.Value);
            if (existBiography == null)
            {
                ViewBag.Message = "Sorry! there is no biography found.";
                await PopulateActors();
                return View(new BiographyEditVM());
            }
            await PopulateActors();
            BiographyEditVM editVM = _mapper.Map<BiographyEditVM>(existBiography);

            return View(editVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(BiographyEditVM biographyEditVM)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Message = "Sorry! Invalid information, please enter valid information.";
                await PopulateActors();
                return View(biographyEditVM);
            }

            //Check Biography exist or not
            Biography? existBiography = await _unitService.BiographyService.GetBiographyByIdAsync(biographyEditVM.BiographyId);

            if (existBiography == null)
            {
                ViewBag.Message = "Sorry! there is not biography found.";
                await PopulateActors();
                return View(biographyEditVM);
            }

            //Maintain the existing file name if no new file is uploaded
            biographyEditVM.DescriptionFileName = existBiography.DescriptionFileName;

            //if a new DescriptionFile is uploaded, remove the old one
            if (biographyEditVM.DescriptionFile != null)
            {
                try
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string descriptionFolder = "description-bio";

                    //Remove the old descriptionfile from wwwroot/description-bio
                    if (!string.IsNullOrEmpty(existBiography.DescriptionFileName))
                    {
                        string oldFilePath = Path.Combine(wwwRootPath, descriptionFolder, existBiography.DescriptionFileName);
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    //Upload new descriptioin file
                    string descriptionFileName = await _fileUpload.ImageOrPdfUploadAsync(biographyEditVM.DescriptionFile, descriptionFolder);

                    if (!string.IsNullOrEmpty(descriptionFileName))
                    {
                        biographyEditVM.DescriptionFileName = descriptionFileName;
                    }
                }
                catch (InvalidOperationException ex)
                {
                    ViewBag.Message = $"Error: {ex.Message}";
                    await PopulateActors();
                    return View(biographyEditVM);
                }
                catch //catch unexpected errors
                {
                    ViewBag.Message = "An unexpected error occurred. Please try again.";
                    await PopulateActors();
                    return View(biographyEditVM);
                }
            }

            //Handle if new biography images(collection) uploaded and remove old images(collection)
            if (biographyEditVM.BioImages != null && biographyEditVM.BioImages.Any())
            {
                try
                {
                    string wwwRootPath = _webHostEnvironment.WebRootPath;
                    string imageFolder = "images-bio";

                    //Remove old biography images if there are any images
                    if (existBiography.BiographyImages.Any())
                    {
                        foreach (var existingImage in existBiography.BiographyImages.ToList())
                        {

11-ActorManagementApp/Views/Actor/Create.cshtml
@model ActorCreateVM

@{
    ViewData["Title"] = "Add Actor";
}

<div class="container">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-info">
            @ViewBag.Message
        </div>        
    }
    <div class="row p-3">
        <div class="col-md-12">
            <h3>Add New Actor</h3>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <form asp-controller="Actor" asp-action="Create" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group mb-3">
                    <label asp-for="FirstName" class="form-label fw-bold"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="LastName" class="form-label fw-bold"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="DateOfBirth" class="form-label fw-bold"></label>
                    <input asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Gender" class="form-label fw-bold"></label>
                    <div class="d-flex">
                        <div class="form-check px-4">
                            <input asp-for="Gender" class="form-check-input" value="male" type="radio" id="genderMale">
                            <label class="form-check-label" for="Gender">
                                Male
                            </label>
                        </div>
                        <div class="form-check px-4">
                            <input asp-for="Gender" class="form-check-input" value="female" type="radio" id="genderFemale">
                            <label class="form-check-label" for="Gender">
                                Female
                            </label>
                        </div>
                        <div class="form-check px-4">
                            <input asp-for="Gender" class="form-check-input" value="other" type="radio" id="genderOther">
                            <label class="form-check-label" for="Gender">
                                Other
                            </label>
                        </div>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Email" class="form-label fw-bold"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <div class="form-check">
                        <input asp-for="IsActive" class="form-check-input" type="checkbox" id="isActive" checked>
                        <label class="form-check-label fw-bold" for="isActive">Mark as Active</label>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Address" class="form-label fw-bold"></label>
                    <textarea asp-for="Address" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group mb-5">
                    <label asp-for="ImageFile" class="form-label fw-bold"></label>
                    <input asp-for="ImageFile" class="form-control" accept="image/*" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <input type="submit" value="Submit" class="btn btn-primary w-50" />
                </div>
            </form>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <a asp-controller="Actor" asp-action="Index" class="btn btn-info">View all Actors</a>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

11-ActorManagementApp/Views/Actor/Details.cshtml
@model ActorDetailsVM

@{
    ViewData["Title"] = "Actor Details";
}

<div class="container">
    <div class="row p-3">
        <div class="col-md-12">
            <h3>Actor @Model.FirstName Details</h3>
        </div>
    </div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateOfBirth)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateOfBirth)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd class="col-sm-10">
            @* @Html.DisplayFor(model => model.IsActive) *@
            @(Model.IsActive ? "Yes" : "No")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayName("Photo")
        </dt>
        <dd class="col-sm-10">
            <img src="@("~/images-actors/" + Model.ImageName)" asp-append-version="true" style="width:250px; border-radius:5px;" />
        </dd>
    </dl>
    <div class="px-3">
        <a asp-controller="Actor" asp-action="Edit" asp-route-email="@Model.Email" class="btn btn-success me-2" title="Edit">Edit</a>
        <a asp-controller="Actor" asp-action="Index" class="btn btn-info">Back to List</a>
    </div>
</div>

11-ActorManagementApp/Views/Actor/Edit.cshtml
@model ActorEditVM

@{
    ViewData["Title"] = "Edit Actor";
}

<div class="container">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-info">
            @ViewBag.Message
        </div>
    }
    <div class="row p-3">
        <div class="col-md-12">
            <h3>Edit Actor</h3>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <form asp-controller="Actor" asp-action="Edit" method="post" enctype="multipart/form-data" autocomplete="off">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="ActorId" />
                <div class="form-group mb-3">
                    <label asp-for="FirstName" class="form-label fw-bold"></label>
                    <input asp-for="FirstName" class="form-control" />
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="LastName" class="form-label fw-bold"></label>
                    <input asp-for="LastName" class="form-control" />
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="DateOfBirth" class="form-label fw-bold"></label>
                    <input asp-for="DateOfBirth" class="form-control" />
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Gender" class="form-label fw-bold"></label>
                    <div class="d-flex">
                        <div class="form-check px-4">
                            <input asp-for="Gender" class="form-check-input" value="male" type="radio" id="genderMale">
                            <label class="form-check-label" for="Gender">
                                Male
                            </label>
                        </div>
                        <div class="form-check px-4">
                            <input asp-for="Gender" class="form-check-input" value="female" type="radio" id="genderFemale">
                            <label class="form-check-label" for="Gender">
                                Female
                            </label>
                        </div>
                        <div class="form-check px-4">
                            <input asp-for="Gender" class="form-check-input" value="other" type="radio" id="genderOther">
                            <label class="form-check-label" for="Gender">
                                Other
                            </label>
                        </div>
                        <span asp-validation-for="Gender" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Email" class="form-label fw-bold"></label>
                    <input asp-for="Email" class="form-control" />
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <div class="form-check">
                        <input asp-for="IsActive" class="form-check-input" type="checkbox" id="isActive" checked>
                        <label class="form-check-label fw-bold" for="isActive">Mark as Active</label>
                    </div>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Address" class="form-label fw-bold"></label>
                    <textarea asp-for="Address" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="Address" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="ImageFile" class="form-label fw-bold"></label>
                    <input asp-for="ImageFile" class="form-control" accept="image/*" />
                    <span asp-validation-for="ImageFile" class="text-danger"></span>
                </div>
                <div class="form-group mb-5">
                    <label asp-for="ImageName" class="form-label fw-bold">Current Photo:</label>
                    <input asp-for="ImageName" class="form-control" value="@Model.ImageName" disabled /><br />
                    <img src="@("~/images-actors/" + Model.ImageName)" asp-append-version="true" style="max-width:150px;" />
                </div>
                <div class="form-group mb-3">
                    <input type="submit" value="Update" class="btn btn-primary w-50" />
                </div>
            </form>
        </div>
    </div>
    <div class="row p-3">
        <div class="col-md-6">
            <a asp-controller="Actor" asp-action="Index" class="btn btn-info">View all Actors</a>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

11-ActorManagementApp/Views/Actor/Index.cshtml
@model IEnumerable<ActorIndexVM>

@{
    ViewData["Title"] = "All Actors";
}

<div class="container">
    @if (ViewBag.Message != null)
    {
        <div class="alert alert-info">
            @ViewBag.Message
        </div>
    }
    @if (TempData["Message"] != null)
    {
        <div class="alert alert-info">
            @TempData["Message"]
        </div>
    }
    <div class="row p-1">
        <div class="col-md-12">
            <h3>All Actors</h3>
        </div>
    </div>
    <div class="row p-1">
        <div class="col-md-8">
            <a asp-controller="Actor" asp-action="Create" class="btn btn-primary me-2">Add New Actor</a>
            <a asp-controller="Biography" asp-action="Add" class="btn btn-success me-2">Add Biography</a>
            <a asp-controller="Actor" asp-action="Index" class="btn btn-info">View All</a>
        </div>
    </div>
    <div class="row p-1">
        <div class="col-md-12">
            <table id="actorsTable" class="table table-striped table-bordered table-success table-responsive">
                <thead>
                    <tr>
                        <th>
                            <label asp-for="@Model.First().FirstName"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.First().LastName"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.First().DateOfBirth"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.First().Gender"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.First().Email"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.First().IsActive"></label>
                        </th>
                        <th>
                            <label asp-for="@Model.First().Address"></label>
                        </th>
                        <th>
                            <label>Image</label>
                        </th>
                        <th>
                            <label>Download Biography</label>
                        </th>
                        <th>
                            <label>All Images</label>
                        </th>
                        <th>
                            <label>Edit</label>
                        </th>
                        <th>
                            <label>Details</label>
                        </th>
                        <th>
                            <label>Delete</label>
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                <span asp-for="@item.FirstName">@item.FirstName</span>
                            </td>
                            <td>
                                <span asp-for="@item.LastName">@item.LastName</span>
                            </td>
                            <td>
                                <span asp-for="@item.DateOfBirth">@item.DateOfBirth.ToShortDateString()</span>
                            </td>
                            <td>
                                <span asp-for="@item.Gender">@item.Gender</span>
                            </td>
                            <td>
                                <span asp-for="@item.Email">@item.Email</span>
                            </td>
                            <td>
                                <span asp-for="@item.IsActive">@(item.IsActive ? "Yes" : "No")</span>
                            </td>
                            <td>
                                <span asp-for="@item.Address">@item.Address</span>
                            </td>
                            <td>
                                <img src="~/images-actors/@item.ImageName" asp-append-version="true" style="width:60px;" />
                            </td>
                            <td>
                                @if (!string.IsNullOrEmpty(item?.Biography?.DescriptionFileName))
                                {
                                    <a asp-controller="Actor" asp-action="DownloadBiography" asp-route-fileName="@item.Biography.DescriptionFileName" class="btn btn-info" title="Download Biography">
                                        <i class="bi bi-cloud-arrow-down"></i>
                                    </a>
                                }
                                else
                                {
                                    <span>No file</span>
                                }
                            </td>
                            <td>
                                <a class="btn btn-outline-info" title="View all @item.FirstName photo" onclick="viewActorImages('@item.Email')">View</a>
                            </td>
                            <td>
                                <a asp-controller="Actor" asp-action="Edit" asp-route-email="@item.Email" class="btn btn-success me-1" title="Edit">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                            </td>
                            <td>
                                <a asp-controller="Actor" asp-action="Details" asp-route-email="@item.Email" class="btn btn-info me-1" title="Details">
                                    <i class="bi bi-info-square"></i>
                                </a>
                            </td>
                            <td>
                                <a asp-controller="Actor" asp-action="Delete" asp-route-email="@item.Email" class="btn btn-danger" title="Delete" onclick="return confirm('Are you sure, you want to delete this actor @item.FirstName')">
                                    <i class="bi bi-trash3"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    <div class="row p-1">
        <div id="actorImagesContainer" class="container mt-4"></div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#actorsTable').DataTable({
                "columnDefs": [
                    { "orderable": false, "targets": [7, 8, 9, 10, 11, 12] }
                ]                 
            });
        });

        function viewActorImages(email) {
            $.ajax({
                url: '/Actor/GetActorImagesPartial',
                type: 'GET',
                data: { email: email },
                success: function (response) {
                    $('#actorImagesContainer').html(response);
                    $('html, body').animate({
                        scrollTop: $('#actorImagesContainer').offset().top
                    }, 500);
                },
                error: function () {
                    alert('Error fetching actor images. Please try again.');
                }
            });
        }
    </script>
}

11-ActorManagementApp/Views/Actor/_ActorImagesPartial.cshtml
@model IEnumerable<string>

<div id="actor-images-container" class="mt-3">
    @if (Model != null && Model.Any())
    {
        <div class="row">
            @foreach (var imageName in Model)
            {
                @if (imageName == "No actor found" || imageName == "No images available")
                {
                    <h4>@imageName</h4>
                }
                else
                {
                    <div class="col-md-3 mb-2">
                        <img src="~/images-bio/@imageName" class="img-thumbnail" style="width:350px;" />
                    </div>
                }                
            }
        </div>
    }
    else
    {
        <h4>No image available</h4>
    }
</div>